#!/bin/sh
# Simple wrapper for invoking from Docker image

cd "$(dirname "$0")"/PulseMonitor
while true; do
    PulseEmail='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
    PulsePass='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
    python3 ./Source/startup.py
    sleep 300
done
