#!/bin/sh
# Simple wrapper for invoking from Docker image

cd "$(dirname "$0")"/PulseMonitor
PulseEmail='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
PulsePass='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
while true; do
    python3 ./Source/startup.py
done
